'use client';

import * as React from 'react';
import { Swords, Trophy, Vote, Users, Copy, CalendarX2 } from 'lucide-react';
import { format, startOfWeek, addDays, isSameDay, isToday } from 'date-fns';

import type { ScheduleEvent, AllVotes, PlayerProfileData } from '@/lib/types';
import { timeSlots, MINIMUM_PLAYERS } from '@/lib/types';
import { cn } from '@/lib/utils';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from '@/components/ui/tooltip';
import {
    Table,
    TableBody,
    TableCell,
    TableHead,
    TableHeader,
    TableRow,
  } from "@/components/ui/table";
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
    DialogFooter,
} from '@/components/ui/dialog';
import { Avatar, AvatarFallback, AvatarImage } from '../ui/avatar';
import { Button } from '../ui/button';
import { useToast } from '@/hooks/use-toast';
import { Separator } from '../ui/separator';
import { Skeleton } from '../ui/skeleton';

type HeatmapGridProps = {
  allVotes: AllVotes;
  scheduledEvents: ScheduleEvent[];
  currentDate: Date;
  allProfiles: PlayerProfileData[] | null;
};

type SelectedSlot = {
    date: Date;
    slot: string;
    players: {id: string, name: string, photoURL?: string | null}[];
} | null;

const heatmapColors = [
    'bg-sky-900/20', // Very few votes
    'bg-sky-800/40',
    'bg-cyan-700/60',
    'bg-teal-600/80',
    'bg-amber-500/80', // Transition to warm
    'bg-amber-400', // Most votes
];

export function HeatmapGrid({
  allVotes,
  scheduledEvents,
  currentDate,
  allProfiles
}: HeatmapGridProps) {
  const [mounted, setMounted] = React.useState(false);
  const [selectedSlot, setSelectedSlot] = React.useState<SelectedSlot>(null);
  const { toast } = useToast();

  React.useEffect(() => {
    setMounted(true);
  }, []);

  const profileMap = React.useMemo(() => {
    if (!allProfiles) return new Map();
    return new Map(allProfiles.map(p => [p.username, p]));
  }, [allProfiles]);

  const allPlayerNames = React.useMemo(() => {
    if (!allProfiles) return [];
    return allProfiles.map(p => p.username).filter(Boolean) as string[];
  }, [allProfiles]);

  const weekDates = React.useMemo(() => {
    const start = startOfWeek(currentDate, { weekStartsOn: 1 });
    return Array.from({ length: 7 }, (_, i) => addDays(start, i));
  }, [currentDate]);

  const maxVotes = React.useMemo(() => {
    return allPlayerNames.length || 1;
  }, [allPlayerNames]);

  const getHeatmapColor = (voteCount: number) => {
    if (voteCount === 0) return 'bg-transparent';
    const percentage = voteCount / maxVotes;
    const colorIndex = Math.min(
        Math.floor(percentage * (heatmapColors.length)),
        heatmapColors.length - 1
    );
    return heatmapColors[colorIndex];
  };
  
  const getEventForSlot = (day: Date, slot: string) => {
    return scheduledEvents.find(event => {
      return isSameDay(event.date, day) && event.time === slot;
    });
  };

  const handleSlotClick = (date: Date, slot: string, players: string[]) => {
    const detailedPlayers = players.map(name => {
      const profile = profileMap.get(name);
      return { 
        id: profile?.id || name, 
        name, 
        photoURL: profile?.photoURL 
      };
    })
    setSelectedSlot({date, slot, players: detailedPlayers});
  };

  const handleCopyList = () => {
    if (!selectedSlot) return;

    const formatPlayerList = (players: string[], profileMap: Map<string, PlayerProfileData>) => {
        if (players.length === 0) return '- None';
        return players
          .map(p => {
            const profile = profileMap.get(p);
            if (profile?.rosterStatus === 'Main Roster') return `- ${p} (Main)`;
            if (profile?.rosterStatus === 'Standby Player') return `- ${p} (Standby)`;
            return `- ${p}`;
          })
          .join('\n');
    };

    const { date, slot, players: availablePlayersWithDetails } = selectedSlot;
    const availablePlayers = availablePlayersWithDetails.map(p => p.name);
    
    const unavailablePlayers = allPlayerNames.filter(p => !availablePlayers.includes(p));
    const neededPlayers = Math.max(0, MINIMUM_PLAYERS - availablePlayers.length);

    const header = `Roster for ${format(date, 'EEEE, d MMM')} at ${slot}:`;
    
    const availableHeader = `✅ Available Players (${availablePlayers.length}):`;
    const availableList = formatPlayerList(availablePlayers, profileMap);
    
    const neededText = `🔥 Players Needed: ${neededPlayers}`;
    
    const unavailableHeader = `❌ Unavailable Players (${unavailablePlayers.length}):`;
    const unavailableList = formatPlayerList(unavailablePlayers, profileMap);

    const footer = `\n---\nGenerated by TeamSync\nhttps://scrimsync.vercel.app/`;

    const fullText = [
        header,
        '',
        availableHeader,
        availableList,
        '',
        neededText,
        '',
        unavailableHeader,
        unavailableList,
        footer
    ].join('\n');
    
    navigator.clipboard.writeText(fullText).then(() => {
        toast({
            title: 'Copied to Clipboard',
            description: 'The roster summary has been copied.',
        });
    }, (err) => {
        console.error('Could not copy text: ', err);
        toast({
            variant: 'destructive',
            title: 'Copy Failed',
            description: 'Could not copy the list to your clipboard.',
        });
    });
  };

  const unavailablePlayers = selectedSlot ? allPlayerNames
    .map(name => profileMap.get(name))
    .filter(profile => profile && !selectedSlot.players.some(p => p.id === profile.id)) : [];

  if (!mounted) {
    return (
      <Card>
        <CardHeader>
          <Skeleton className="h-8 w-1/3" />
        </CardHeader>
        <CardContent>
          <Skeleton className="h-64 w-full" />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
            <Vote className="w-6 h-6 text-gold" />
            <CardTitle>Team Availability Heatmap</CardTitle>
            </div>
        </div>
        <CardDescription>
          Darker slots indicate higher player availability. Click a slot to see who is available.
        </CardDescription>
      </CardHeader>
      <CardContent>
        <TooltipProvider>
            <div className="border rounded-lg overflow-auto max-h-[65vh] relative">
                <Table className="w-full border-collapse">
                    <TableHeader className="sticky top-0 z-30 bg-muted/50 backdrop-blur-sm border-b-2 border-border">
                        <TableRow>
                            <TableHead className="w-[100px] sticky left-0 bg-muted/50 backdrop-blur-sm z-40 text-center font-bold">Time</TableHead>
                            {weekDates.map(date => (
                                <TableHead key={date.toISOString()} className={cn("text-center p-2", isToday(date) && "bg-gold-10")}>
                                  <div className='min-w-[6rem] font-bold'>{format(date, 'EEE')}</div>
                                  <div className="font-normal text-muted-foreground">{format(date, 'd/M')}</div>
                                </TableHead>
                            ))}
                        </TableRow>
                    </TableHeader>
                    <TableBody>
                        {timeSlots.map(slot => (
                            <TableRow key={slot}>
                                <TableCell className="font-medium sticky left-0 bg-card/95 backdrop-blur-sm z-20 p-2">{slot}</TableCell>
                                {weekDates.map(date => {
                                    const dateKey = format(date, 'yyyy-MM-dd');
                                    const voteKey = `${dateKey}-${slot}`;
                                    const availablePlayers = allVotes[voteKey] || [];
                                    const voteCount = availablePlayers.length;
                                    const event = getEventForSlot(date, slot);
                                    const isCancelled = event?.status === 'Cancelled';
                                    return (
                                        <TableCell key={date.toISOString()} className="text-center p-0 align-middle">
                                            <Tooltip>
                                                <TooltipTrigger asChild>
                                                    <div
                                                        onClick={() => handleSlotClick(date, slot, availablePlayers)}
                                                        className={cn(
                                                            'relative h-14 w-full flex flex-col justify-center items-center text-center p-1 transition-all duration-300 cursor-pointer border-l border-t border-border glow-on-hover',
                                                            isCancelled ? 'bg-destructive/20' : getHeatmapColor(voteCount),
                                                            isToday(date) && !isCancelled && 'bg-gold-10'
                                                        )}
                                                    >
                                                        <div className={cn("relative z-10 text-sm font-bold", isCancelled ? 'text-destructive-foreground' : 'text-foreground/90')}>
                                                            {!isCancelled && voteCount > 0 ? voteCount : ''}
                                                        </div>
                                                        {event && (
                                                            <div className="absolute top-1 right-1 z-20">
                                                            {isCancelled ? (
                                                                <CalendarX2 className="w-4 h-4 text-destructive-foreground/80" />
                                                            ) : event.type === 'Training' ? (
                                                                <Swords className="w-4 h-4 text-foreground/80" />
                                                            ) : (
                                                                <Trophy className="w-4 h-4 text-gold" />
                                                            )}
                                                            </div>
                                                        )}
                                                    </div>
                                                </TooltipTrigger>
                                                <TooltipContent>
                                                    <p>{format(date, 'EEEE, d MMM')} at {slot}</p>
                                                    <p>{voteCount} players available</p>
                                                    {event && (
                                                    <p className={cn("mt-1 font-bold", isCancelled && "text-destructive")}>
                                                        {event.type} {isCancelled ? "Cancelled" : "scheduled"}
                                                    </p>
                                                    )}
                                                </TooltipContent>
                                            </Tooltip>
                                        </TableCell>
                                    )
                                })}
                            </TableRow>
                        ))}
                    </TableBody>
                </Table>
            </div>
        </TooltipProvider>

        <Dialog open={!!selectedSlot} onOpenChange={(isOpen) => !isOpen && setSelectedSlot(null)}>
            <DialogContent className='max-w-md'>
                <DialogHeader>
                    <DialogTitle>Roster Details</DialogTitle>
                    {selectedSlot && (
                        <DialogDescription>
                            {format(selectedSlot.date, 'EEEE, d MMM')} at {selectedSlot.slot}
                        </DialogDescription>
                    )}
                </DialogHeader>
                <div className='max-h-[60vh] overflow-y-auto space-y-4'>
                    {selectedSlot && (
                        <>
                            <div>
                                <h4 className='font-semibold mb-2 text-sm'>✅ Available ({selectedSlot.players.length})</h4>
                                {selectedSlot.players.length > 0 ? (
                                    <ul className='space-y-2'>
                                    {selectedSlot.players.map(player => (
                                        <li key={player.id} className='flex items-center gap-3 text-sm'>
                                            <Avatar className='h-6 w-6'>
                                                <AvatarImage src={player.photoURL ?? `https://api.dicebear.com/8.x/pixel-art/svg?seed=${player.id}`} />
                                                <AvatarFallback>{player.name.charAt(0).toUpperCase()}</AvatarFallback>
                                            </Avatar>
                                            <span className='font-medium'>{player.name}</span>
                                        </li>
                                    ))}
                                    </ul>
                                ) : (
                                    <p className='text-sm text-muted-foreground italic'>No players available.</p>
                                )}
                            </div>
                            <Separator />
                             <div>
                                <h4 className='font-semibold mb-2 text-sm'>❌ Unavailable ({unavailablePlayers.length})</h4>
                                {unavailablePlayers.length > 0 ? (
                                    <ul className='space-y-2'>
                                    {unavailablePlayers.map(player => player && (
                                        <li key={player.id} className='flex items-center gap-3 text-sm text-muted-foreground'>
                                            <Avatar className='h-6 w-6'>
                                                <AvatarImage src={player.photoURL ?? `https://api.dicebear.com/8.x/pixel-art/svg?seed=${player.id}`} />
                                                <AvatarFallback>{player.username.charAt(0).toUpperCase()}</AvatarFallback>
                                            </Avatar>
                                            <span>{player.username}</span>
                                        </li>
                                    ))}
                                    </ul>
                                ) : (
                                    <p className='text-sm text-muted-foreground italic'>All players are available.</p>
                                )}
                            </div>
                        </>
                    )}
                    {!selectedSlot && (
                        <div className='flex flex-col items-center justify-center text-center py-12'>
                            <Users className='w-12 h-12 text-muted-foreground' />
                            <p className='mt-4 text-muted-foreground'>No slot selected.</p>
                        </div>
                    )}
                </div>
                <DialogFooter className='sm:justify-between items-center gap-2 pt-4'>
                    {selectedSlot && (
                         <div className='text-sm text-center sm:text-left'>
                            <span className='font-bold'>{Math.max(0, MINIMUM_PLAYERS - selectedSlot.players.length)}</span> players needed for a roster of {MINIMUM_PLAYERS}.
                        </div>
                    )}
                    <Button onClick={handleCopyList} disabled={!selectedSlot}>
                        <Copy className='w-4 h-4 mr-2' />
                        Copy Roster
                    </Button>
                </DialogFooter>
            </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  );
}
