'use client';

import * as React from 'react';
import { format, startOfToday, differenceInMinutes, isToday } from 'date-fns';
import { CalendarCheck, Users, Trash2, Copy } from 'lucide-react';
import type { User } from 'firebase/auth';

import type { AllVotes, ScheduleEvent } from '@/lib/types';
import { MINIMUM_PLAYERS } from '@/lib/types';
import { useToast } from '@/hooks/use-toast';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card';
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Avatar, AvatarFallback, AvatarImage } from '../ui/avatar';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '@/components/ui/alert-dialog';
import { ScrollArea } from '../ui/scroll-area';
import { cn } from '@/lib/utils';

type ScheduledEventsProps = {
  events: ScheduleEvent[];
  votes: AllVotes;
  allPlayerNames: string[];
  onRemoveEvent: (eventId: string) => void;
  currentUser: User | null;
};

export function ScheduledEvents({ events, votes, allPlayerNames, onRemoveEvent, currentUser }: ScheduledEventsProps) {
    const { toast } = useToast();
    const [now, setNow] = React.useState(new Date());

    React.useEffect(() => {
        const timer = setInterval(() => {
            setNow(new Date());
        }, 60000); // Update every minute
        return () => clearInterval(timer);
    }, []);
    
    const upcomingEvents = React.useMemo(() => {
        if (!events) return [];
        const today = startOfToday();
        return events
            .filter(event => event.date >= today)
            .sort((a,b) => a.date.getTime() - b.date.getTime());
    }, [events]);

    const getAvailablePlayers = (event: ScheduleEvent): string[] => {
        const dateKey = format(event.date, 'yyyy-MM-dd');
        const voteKey = `${dateKey}-${event.time}`;
        return votes[voteKey] || [];
    };

    const formatTimeRemaining = (eventDate: Date, eventTime: string) => {
        const [time, modifier] = eventTime.split(' ');
        let [hours, minutes] = time.split(':').map(Number);
    
        if (modifier === 'PM' && hours !== 12) {
          hours += 12;
        }
        if (modifier === 'AM' && hours === 12) {
          hours = 0;
        }
    
        const eventDateTime = new Date(eventDate);
        eventDateTime.setHours(hours, minutes, 0, 0);

        const totalMinutes = differenceInMinutes(eventDateTime, now);

        if (totalMinutes <= 0) {
            return 'Started';
        }

        const daysLeft = Math.floor(totalMinutes / (60 * 24));
        const hoursLeft = Math.floor((totalMinutes % (60*24)) / 60);
        const minutesLeft = totalMinutes % 60;
        
        let result = 'in';
        if (daysLeft > 0) result += ` ${daysLeft}d`;
        if (hoursLeft > 0) result += ` ${hoursLeft}h`;
        if (daysLeft === 0 && minutesLeft > 0) result += ` ${minutesLeft}m`;
        
        return result;
    };
    
    const handleCopyList = (event: ScheduleEvent, availablePlayers: string[]) => {
        const unavailablePlayers = allPlayerNames.filter(p => !availablePlayers.includes(p));
        const neededPlayers = Math.max(0, MINIMUM_PLAYERS - availablePlayers.length);

        const timeRemaining = formatTimeRemaining(event.date, event.time);
        const header = `Roster for ${event.type} on ${format(event.date, 'EEEE, d MMM')} at ${event.time} (starts ${timeRemaining}):`;
        
        const availableHeader = `✅ Available Players (${availablePlayers.length}):`;
        const availableList = availablePlayers.length > 0 ? availablePlayers.map(p => `- ${p}`).join('\n') : '- None';
        
        const neededText = `🔥 Players Needed: ${neededPlayers}`;
        
        const unavailableHeader = `❌ Unavailable Players (${unavailablePlayers.length}):`;
        const unavailableList = unavailablePlayers.length > 0 ? unavailablePlayers.map(p => `- ${p}`).join('\n') : '- None';

        const footer = `\n---\nGenerated by TeamSync\nhttps://scrimsync.vercel.app/`;

        const fullText = [
            header,
            '',
            availableHeader,
            availableList,
            '',
            neededText,
            '',
            unavailableHeader,
            unavailableList,
            footer
        ].join('\n');
        
        navigator.clipboard.writeText(fullText).then(() => {
            toast({
                title: 'Copied to Clipboard',
                description: 'The roster summary has been copied.',
            });
        }, (err) => {
            console.error('Could not copy text: ', err);
            toast({
                variant: 'destructive',
                title: 'Copy Failed',
                description: 'Could not copy the list to your clipboard.',
            });
        });
    };

    return (
        <Card>
            <CardHeader>
                <div className="flex items-center gap-3">
                <CalendarCheck className="w-6 h-6" />
                <CardTitle>Upcoming Events</CardTitle>
                </div>
                <CardDescription>
                Here are your team's scheduled sessions.
                </CardDescription>
            </CardHeader>
            <CardContent className='p-0'>
                {upcomingEvents.length > 0 ? (
                <ScrollArea className='h-[400px]'>
                    <Accordion type="single" collapsible className="w-full">
                        {upcomingEvents.map((event) => {
                        const availablePlayers = getAvailablePlayers(event);
                        const canDelete = currentUser?.uid === event.creatorId;

                        return (
                            <AccordionItem key={event.id} value={event.id} className="px-6">
                            <AccordionTrigger>
                                <div className="flex justify-between items-center w-full pr-2">
                                    <div className='flex flex-col items-start text-left'>
                                        <div className='flex items-center gap-2'>
                                            <Badge variant={event.type === 'Tournament' ? 'default' : 'secondary'}>{event.type}</Badge>
                                            <span className={cn('font-semibold', isToday(event.date) && 'text-primary')}>{format(event.date, 'EEEE, d MMM')}</span>
                                            {isToday(event.date) && <Badge variant="outline">Today</Badge>}
                                        </div>
                                        <div className='flex items-baseline gap-2'>
                                            <span className='text-sm text-muted-foreground'>{event.time}</span>
                                            <span className='text-xs text-primary/80 font-medium'>{formatTimeRemaining(event.date, event.time)}</span>
                                        </div>
                                    </div>
                                </div>
                            </AccordionTrigger>
                            <AccordionContent>
                                <div className='flex justify-between items-start gap-4'>
                                    <div className='flex-grow'>
                                        <div className='mb-2'>
                                            <span className='font-semibold'>{availablePlayers.length}</span> players available. <span className='text-muted-foreground'>{Math.max(0, MINIMUM_PLAYERS - availablePlayers.length)} more needed.</span>
                                        </div>
                                        {availablePlayers.length > 0 ? (
                                        <ul className="space-y-3">
                                            {availablePlayers.map((player) => (
                                            <li key={player} className="flex items-center gap-3">
                                                <Avatar className="h-8 w-8">
                                                <AvatarImage
                                                    src={`https://api.dicebear.com/8.x/pixel-art/svg?seed=${player}`}
                                                />
                                                <AvatarFallback>
                                                    {player.charAt(0).toUpperCase()}
                                                </AvatarFallback>
                                                </Avatar>
                                                <span className="font-medium">{player}</span>
                                            </li>
                                            ))}
                                        </ul>
                                        ) : (
                                        <div className="flex flex-col items-center justify-center text-center py-6">
                                            <Users className="w-10 h-10 text-muted-foreground" />
                                            <p className="mt-3 text-muted-foreground">
                                            No players have marked themselves as available yet.
                                            </p>
                                        </div>
                                        )}
                                    </div>
                                    <div className="flex flex-col items-center gap-2 shrink-0">
                                        {canDelete && (
                                            <AlertDialog>
                                                <AlertDialogTrigger asChild>
                                                    <Button variant="ghost" size="icon" className="text-destructive hover:text-destructive h-8 w-8">
                                                        <Trash2 className="w-4 h-4" />
                                                    </Button>
                                                </AlertDialogTrigger>
                                                <AlertDialogContent>
                                                    <AlertDialogHeader>
                                                    <AlertDialogTitle>Are you sure?</AlertDialogTitle>
                                                    <AlertDialogDescription>
                                                        This action cannot be undone. This will permanently delete the scheduled {event.type.toLowerCase()}.
                                                    </AlertDialogDescription>
                                                    </AlertDialogHeader>
                                                    <AlertDialogFooter>
                                                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                                                    <AlertDialogAction onClick={() => onRemoveEvent(event.id)} className="bg-destructive hover:bg-destructive/90">
                                                        Delete
                                                    </AlertDialogAction>
                                                    </AlertDialogFooter>
                                                </AlertDialogContent>
                                            </AlertDialog>
                                        )}
                                        <Button
                                            variant="outline"
                                            size="icon"
                                            className="h-8 w-8"
                                            onClick={() => handleCopyList(event, availablePlayers)}
                                        >
                                            <Copy className="w-4 h-4" />
                                        </Button>
                                    </div>
                                </div>
                            </AccordionContent>
                            </AccordionItem>
                        );
                        })}
                    </Accordion>
                </ScrollArea>
                ) : (
                <div className="flex flex-col items-center justify-center text-center py-10 px-6">
                    <CalendarCheck className="w-12 h-12 text-muted-foreground" />
                    <p className="mt-4 text-muted-foreground">
                    No upcoming events scheduled.
                    </p>
                </div>
                )}
            </CardContent>
        </Card>
    );
}

    